apiVersion: v1
kind: Service
metadata:
  name: go-vault-service
spec:
  selector:
    app: go-vault
  type: NodePort
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30080  # kamu bisa ubah ini kalau port bentrok
